spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    password: user123
    username: user
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: update

